name: Deploy to Oracle VM

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 1: Repo cleanup
      - name: Repo cleanup
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/data/EvidencijaNezaposlenih
            git reset --hard
            git clean -fdx

      # Step 2: Checkout master and pull latest
      - name: Checkout master
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/data/EvidencijaNezaposlenih
            git checkout master
            git pull origin master

      # Step 3: Stop containers
      - name: Stop containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/data/EvidencijaNezaposlenih
            docker compose down

      # Step 4: Build containers
      - name: Build containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/data/EvidencijaNezaposlenih
            docker compose pull

      # Step 5: Start containers
      - name: Start containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            cd ~/data/EvidencijaNezaposlenih
            docker compose up -d

      # Step 5.5: Wait for 20 seconds
      - name: Wait for containers to stabilize
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            sleep 30

      # Step 6: Verify running containers
      - name: Verify containers
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            docker ps

      - name: Print Server IP
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VM_HOST }}
          username: ubuntu
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            curl -4 ifconfig.me
